name : "Bug Report"
description : "Report an error you're encountering with Mops Bot."
labels : [ bug ]
body :
  - type : markdown
    attributes :
      value : |
        Thank you for reporting an issue to us!
  - type : dropdown
    id : repo_choice
    attributes :
      label : "Repository"
      description : "Which repository is this bug in?"
      options :
        - Mops-Bot
        - Mops-Bot-API
        - Mops-API-Wrapper
        - Mops-Bot-Site
    validations :
      required : true
  - type : dropdown
    id : bug_type
    attributes :
      label : "Bug type"
      description : "If this is a bug in Mops-Bot (Discord Bot), which type of bug is it?"
      options :
        - Slash Commands
        - Commands
        - Events
    validations :
      required : false

  - type : textarea
    id : describe-bug
    attributes :
      label : Description of the bug?
      description : Describe the bug in as much detail as possible by including the steps to reproduce it and the expected behavior.
      placeholder : I can't see the daily cat picture. I went to the cat picture page and clicked on the daily picture. I'm still not seeing the picture.
    validations :
      required : true

  - type : textarea
    id : additional-info
    attributes :
      label : Additional information
      description : Any additional information you'd like to provide?
      placeholder : I'm using Docker on Arch Linux

  - type : textarea
    id : logs
    attributes :
      label : Relevant log output
      description : Please copy and paste any relevant log output. This will be automatically formatted into code.
      render : shell